MD updates, usage updates

diff --git a/src/func/download b/src/func/download
--- a/src/func/download
+++ b/src/func/download
@@ -7,11 +7,22 @@ download_Template()
 	tmp="$(find /tmp/monero-bash.*)"
 	if [[ $downloadMonero = "true" ]]; then
 		wget -P "$tmp" -q --show-progress --content-disposition "$link"
+		code_Wget
 	else
 		link="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/releases/latest" \
 			| grep -o "https://github.com/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
 			| sed 's/\"//g')"
 		wget -P "$tmp" -q --show-progress "$link"
+		if [[ $? != "0" ]]; then
+			$ired; echo "GitHub API error detected..."
+			$white; echo "Trying GitHub HTML filter instead..."
+			link="$(wget -qO- "https://github.com/$AUTHOR/$PROJECT/releases/latest" \
+				| grep -o "/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
+				| awk '{print $1}' \
+				| sed 's/\"//g')"
+			wget -P "$tmp" -q --show-progress "https://github.com/$link"
+			code_Wget
+		fi
 	fi
 }
 download_Monero()
diff --git a/src/func/version b/src/func/version
--- a/src/func/version
+++ b/src/func/version
@@ -5,30 +5,41 @@
 #						turns them into usable variables
 version_Template()
 {
-	NewVer="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/tags" | grep -m1 "name" | awk '{print $2}' | tr -d '\",')"
+	link="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/tags")"
+		if [[ $? != "0" ]]; then
+			$ired; echo "GitHub API error detected..."
+			$white; echo "Trying GitHub HTML filter instead..."
+			NewVer="$(wget -qO- https://github.com/$AUTHOR/$PROJECT/releases/latest \
+				| grep -o "/$AUTHOR/$PROJECT/releases/tag/.*\"" \
+				| awk '{print $1}' | head -n1 \
+				| sed "s@/$AUTHOR/$PROJECT/releases/tag/@@g" | tr -d '"')"
+			[[ $NewVer = "" ]]&& error_Exit "GitHub HTML filter failed..."
+		else
+			NewVer="$(echo "$link" | grep -m1 "name" | awk '{print $2}' | tr -d '\",')"
+		fi
 }
-version_NewMonero()
+version_Monero()
 {
 	local AUTHOR="monero-project"
 	local PROJECT="monero"
 	version_Template
 }
 
-version_NewMoneroBash()
+version_MoneroBash()
 {
 	local AUTHOR="hinto-janaiyo"
 	local PROJECT="monero-bash"
 	version_Template
 }
 
-version_NewXMRig()
+version_XMRig()
 {
 	local AUTHOR="xmrig"
 	local PROJECT="xmrig"
 	version_Template
 }
 
-version_NewP2Pool()
+version_P2Pool()
 {
 	local AUTHOR="SChernykh"
 	local PROJECT="p2pool"
