!!

diff --git a/src/func/download b/src/func/download
--- a/src/func/download
+++ b/src/func/download
@@ -13,8 +13,8 @@ download_Template()
 			| grep -o "https://github.com/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
 			| sed 's/\"//g')"
 		wget -P "$tmp" -q --show-progress "$link"
-		if [[ $? = "8" ]]; then
-			$ired; echo "GitHub API ratelimit detected..."
+		if [[ $? != "0" ]]; then
+			$ired; echo "GitHub API error detected..."
 			$white; echo "Trying GitHub HTML filter instead..."
 			link="$(wget -qO- "https://github.com/$AUTHOR/$PROJECT/releases/latest" \
 				| grep -o "/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
diff --git a/src/func/version b/src/func/version
--- a/src/func/version
+++ b/src/func/version
@@ -6,8 +6,8 @@
 version_Template()
 {
 	local link="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/tags")"
-		if [[ $? = "8" ]]; then
-			$ired; echo "GitHub API ratelimit detected..."
+		if [[ $? != "0" ]]; then
+			$ired; echo "GitHub API error detected..."
 			$white; echo "Trying GitHub HTML filter instead..."
 			NewVer="$(wget -qO- https://github.com/$AUTHOR/$PROJECT/releases/latest \
 				| grep -o "/$AUTHOR/$PROJECT/releases/tag/.*\"" \
