refactoring upgrade, version_ now reuses GitHub $DUMP instead of fetching again (upgrades should be a lot faster)

diff --git a/src/func/download b/src/func/download
--- a/src/func/download
+++ b/src/func/download
@@ -1,34 +1,45 @@
 #!/usr/bin/env bash
 #
-#						Download Functions
-#
+# Download Functions
+# the "$DUMP" variable is reused in
+# "version_" functions so there only needs
+# to be 1 http request for all the data needed
 download_Template()
 {
 	tmp="$(find /tmp/monero-bash.*)"
+	HTML="false"
+	DUMP="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/releases/latest")"
+	if [[ $? != "0" ]]; then
+		$ired; echo "GitHub API error detected..."
+		$white; echo "Trying GitHub HTML filter instead..."
+		DUMP="$(wget -qO- "https://github.com/$AUTHOR/$PROJECT/releases/latest")"
+		HTML="true"
+	fi
 	if [[ $downloadMonero = "true" ]]; then
 		wget -P "$tmp" -q --show-progress --content-disposition "$link"
 		code_Wget
 	else
-		link="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/releases/latest" \
-			| grep -o "https://github.com/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
-			| sed 's/\"//g')"
-		wget -P "$tmp" -q --show-progress "$link"
-		if [[ $? != "0" ]]; then
-			$ired; echo "GitHub API error detected..."
-			$white; echo "Trying GitHub HTML filter instead..."
-			link="$(wget -qO- "https://github.com/$AUTHOR/$PROJECT/releases/latest" \
+		if [[ "$HTML" = "true" ]]; then
+			local link="$(echo "$DUMP" \
 				| grep -o "/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
 				| awk '{print $1}' \
-				| sed 's/\"//g')"
-			wget -P "$tmp" -q --show-progress "https://github.com/$link"
-			code_Wget
+				| tr -d '"' \
+				| sed 's@^@https://github.com@')"
+		else
+			local link="$(echo "$DUMP" \
+				| grep -o "https://github.com/$AUTHOR/$PROJECT/releases/download/.*/$PACKAGE" \
+				| tr -d '"')"
 		fi
+		wget -P "$tmp" -q --show-progress "$link"
+		code_Wget
 	fi
 }
 download_Monero()
 {
 	local link="https://downloads.getmonero.org/cli/linux64"
 	local downloadMonero="true"
+	local AUTHOR="monero-project"
+	local PROJECT="monero"
 	download_Template
 }
 
diff --git a/src/func/version b/src/func/version
--- a/src/func/version
+++ b/src/func/version
@@ -1,23 +1,42 @@
 #!/usr/bin/env bash
 #
-#						Version Functions
-#						these fetch the new version and
-#						turns them into usable variables
-version_Template()
+# Version Functions
+# fetchs latest version, defines it as a variable
+
+# invoked by "monero-bash update"
+version_Update()
 {
 	link="$(wget -qO- "https://api.github.com/repos/$AUTHOR/$PROJECT/tags")"
-		if [[ $? != "0" ]]; then
-			$ired; echo "GitHub API error detected..."
-			$white; echo "Trying GitHub HTML filter instead..."
-			NewVer="$(wget -qO- https://github.com/$AUTHOR/$PROJECT/releases/latest \
-				| grep -o "/$AUTHOR/$PROJECT/releases/tag/.*\"" \
-				| awk '{print $1}' | head -n1 \
-				| sed "s@/$AUTHOR/$PROJECT/releases/tag/@@g" | tr -d '"')"
-			[[ $NewVer = "" ]]&& error_Exit "GitHub HTML filter failed..."
-		else
-			NewVer="$(echo "$link" | grep -m1 "name" | awk '{print $2}' | tr -d '\",')"
-		fi
+	if [[ $? != "0" && "$HTML" != "true" ]]; then
+		$ired; echo "GitHub API error detected..."
+		$white; echo "Trying GitHub HTML filter instead..."
+		HTML="true"
+	fi
+	if [[ "$HTML" = "true" ]]; then
+		NewVer="$(wget -qO- https://github.com/$AUTHOR/$PROJECT/releases/latest \
+			| grep -o "/$AUTHOR/$PROJECT/releases/tag/.*\"" \
+			| awk '{print $1}' | head -n1 \
+			| sed "s@/$AUTHOR/$PROJECT/releases/tag/@@g" | tr -d '"')"
+		[[ $NewVer = "" ]]&& error_Exit "GitHub HTML filter failed..."
+	else
+		NewVer="$(echo "$link" | grep -m1 "name" | awk '{print $2}' | tr -d '\",')"
+	fi
 }
+
+# invoked by "download_Template" function, reuses the "$DUMP" variable
+version_Template()
+{
+	if [[ "$HTML" = "true" ]]; then
+		NewVer="$(echo "$DUMP" \
+			| grep -o "/$AUTHOR/$PROJECT/releases/tag/.*\"" \
+			| awk '{print $1}' | head -n1 \
+			| sed "s@/$AUTHOR/$PROJECT/releases/tag/@@g" | tr -d '"')"
+		[[ $NewVer = "" ]]&& error_Exit "GitHub HTML filter failed..."
+	else
+		NewVer="$(echo "$DUMP" | grep "tag_name.*v.*" | awk '{print $2}' | tr -d '",')"
+	fi
+}
+
 version_Monero()
 {
 	local AUTHOR="monero-project"
