SOURCE CODE REHAUL pt.2

diff --git a/monero-bash b/monero-bash
--- a/monero-bash
+++ b/monero-bash
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
 
-# check for /monero-bash/ directory, sourcing, interactive/options
+# check for crucial monero-bash source files
 scriptPath="$(realpath $0)"
 installDirectory="$(dirname "$scriptPath")"
 if [[ $installDirectory == *"/monero-bash" ]]; then
 	cd "$installDirectory"
 	source "$installDirectory/src/all"
-	if [[ $? = "1" ]]; then
-		printf "\033[1;31mERROR: monero-bash sourcing error:\n"
+	if [[ $? != "0" ]]; then
 		[[ $varMissing = "true" ]]&& printf "\033[1;37mVariables not sourced\n"
 		[[ $funcMissing = "true" ]]&& printf "\033[1;37mFunctions not sourced\n"
         [[ $stateMissing = "true" ]]&& printf "\033[1;37mmonero-bash state file missing\n"
@@ -19,10 +18,13 @@ if [[ $installDirectory == *"/monero-bash" ]]; then
 	[[ $1 = "" ]]&& interactive="true"
 	[[ $1 != "" ]]&& options="true"
 else
-	printf "\033[1;31mExecuting monero-bash while it isn't in the /monero-bash/ folder is dangerous\n"
+	printf "\033[1;31mExecuting monero-bash while it isn't in the /monero-bash/ folder is DANGEROUS\n"
 	printf "\033[0;31mExiting for safety...\n"
 	exit
 fi
+
+# even more safety checks
+#safety_MoneroBashFolder
 
 # DEBUG COMMANDS
 if [[ $1 = "DEBUG" ]]; then
@@ -35,9 +37,10 @@ if [[ $1 = "DEBUG" ]]; then
 	exit
 fi
 
-# Interactive Config
-if [[ $FIRST_TIME = "true" && $1 = "" ]]; then
-	config_Interactive
+# Installation
+if [[ $FIRST_TIME = "true" ]]; then
+	monerobash_Install
+	exit
 fi
 
 #
@@ -56,7 +59,7 @@ if [[ $interactive = "true" ]]; then
 		$white; echo -n ": "
 		read walletSelection
 		if [[ $walletSelection = "" ]]; then
-			$ired; echo "Error: empty input" ;$off
+			$ired; echo "monero-bash error: empty input" ;$off
 			exit
 		fi
 		if [[ $walletList = *"$walletSelection"* ]]; then
@@ -68,7 +71,7 @@ if [[ $interactive = "true" ]]; then
 			wallet_Create
 			break
 		else
-			$ired; echo "Error: wallet does not exist"
+			$ired; echo "monero-bash error: wallet does not exist"
 		fi
 	done
 	exit
@@ -120,10 +123,7 @@ if [[ $options = "true" ]]; then
 			esac
 			;;
 		list) wallet_Count && wallet_List ;;
-		size)
-			echo -n "/monero-bash/ size: "
-			du -h "$installDirectory" | tail -n 1 | awk '{print $1}'
-			;;
+		size) print_Size ;;
 		price) check_Price ;;
 		help) print_Usage ;;
 		*)
diff --git a/src/debug b/src/debug
--- a/src/debug
+++ b/src/debug
@@ -40,37 +40,74 @@ PRODUCE_HASH_LIST()
 			sha256sum $i >> "$hashlist"
 		fi
 	done
+	# txt hashes
+	for i in src/txt/* ;do
+		if [[ -f "$i" && "$i" != "src/txt/hashlist" ]]; then
+			sha256sum $i >> "$hashlist"
+		fi
+	done
 }
 
 # check hash list against current monero-bash files (with color coded output)
 CHECK_HASH_LIST()
 {
 	# monero-bash hash
-	grep "monero-bash" "$hashlist" &>/dev/null | sha256sum -c &>/dev/null
-	echo -n "monero-bash: "
-	if [[ $? = 0 ]]; then
+	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
+	if [[ $? = "0" ]]; then
+		echo -n "monero-bash: "
 		$igreen; echo "OK" ;$white
 	else
+		echo -n "monero-bash: "
 		$bred; echo "FAILED" ;$white
+		hashFail="true"
 	fi
 	# src file hashes
 	for i in src/* ;do
-		grep "$i" "$hashlist" &>/dev/null | sha256sum -c &>/dev/null
-		echo -n "$i: "
-		if [[ $? = 0 ]]; then
-			$igreen; echo "OK" ;$white
-		else
-			$bred; echo "FAILED" ;$white
+		if [[ -f "$i" ]]; then
+			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+			if [[ $? = "0" ]]; then
+				echo -n "$i: "
+				$igreen; echo "OK" ;$white
+			else
+				echo -n "$i: "
+				$bred; echo "FAILED" ;$white
+				hashFail="true"
+			fi
 		fi
 	done
 	# function hashes
 	for i in src/func/* ;do
-		grep "$i" "$hashlist" &>/dev/null | sha256sum -c &>/dev/null
-		echo -n "$i: "
-		if [[ $? = 0 ]]; then
+		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+		if [[ $? = "0" ]]; then
+			echo -n "$i: "
 			$igreen; echo "OK" ;$white
 		else
+			echo -n "$i: "
 			$bred; echo "FAILED" ;$white
+			hashFail="true"
 		fi
 	done
+	# txt hashes
+	for i in src/txt/* ;do
+		if [[ $i != "src/txt/hashlist" ]]; then
+			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+			if [[ $? = "0" ]]; then
+				echo -n "$i: "
+				$igreen; echo "OK" ;$white
+			else
+				echo -n "$i: "
+				$bred; echo "FAILED" ;$white
+				hashFail="true"
+			fi
+		fi
+	done
+	if [[ $hashFail = "true" ]]; then
+		$bred; echo -n "monero-bash error: "
+		$bwhite; echo "hash check has failed"
+		$white; echo "Exiting for safety..."
+		exit 1
+	else
+		$bwhite; echo -n "monero-bash: "
+		$bgreen; echo "hash check success!"
+	fi
 }
