SOURCE CODE REHAUL pt.3

diff --git a/src/debug b/src/debug
--- a/src/debug
+++ b/src/debug
@@ -5,9 +5,10 @@
 #
 
 # invoke a monero-bash function directly
-DEBUG()
+DEBUG_04e3be9()
 {
-	$iwhite; echo -n "input: "
+	$bred; echo "@@@@@@   DEBUG MODE - BE CAREFUL   @@@@@@"
+	$iwhite; echo -n "function to execute: " ;$off
 	read command
 	"$command"
 }
@@ -21,29 +22,36 @@ LIST()
 	cat "src/var" | grep -v "#" | grep -v "\033"
 }
 
+# puts installed packages into variables
+#WHICH_PACKAGES()
+#{
+#	
+#}
+
 # produce a hash list for important monero-bash files /monero-bash/src/txt/hashlist
 PRODUCE_HASH_LIST()
 {
+	prompt_Sudo
 	echo "producing $hashlist"
-	echo -n > "$hashlist"
+	sudo echo -n > "$hashlist"
 	# monero-bash hash
-	sha256sum "monero-bash" >> "$hashlist"
+	sudo sha256sum "monero-bash" >> "$hashlist"
 	# src file hashes
 	for i in src/* ;do
 		if [[ -f "$i" ]]; then
-			sha256sum $i >> "$hashlist"
+			sudo sha256sum $i >> "$hashlist"
 		fi
 	done
 	# function hashes
 	for i in src/func/* ;do
 		if [[ -f "$i" ]]; then
-			sha256sum $i >> "$hashlist"
+			sudo sha256sum $i >> "$hashlist"
 		fi
 	done
 	# txt hashes
 	for i in src/txt/* ;do
 		if [[ -f "$i" && "$i" != "src/txt/hashlist" ]]; then
-			sha256sum $i >> "$hashlist"
+			sudo sha256sum $i >> "$hashlist"
 		fi
 	done
 }
@@ -55,7 +63,7 @@ CHECK_HASH_LIST()
 	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
 	if [[ $? = "0" ]]; then
 		echo -n "monero-bash: "
-		$igreen; echo "OK" ;$white
+		$bgreen; echo "OK" ;$white
 	else
 		echo -n "monero-bash: "
 		$bred; echo "FAILED" ;$white
@@ -67,7 +75,7 @@ CHECK_HASH_LIST()
 			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
 			if [[ $? = "0" ]]; then
 				echo -n "$i: "
-				$igreen; echo "OK" ;$white
+				$bgreen; echo "OK" ;$white
 			else
 				echo -n "$i: "
 				$bred; echo "FAILED" ;$white
@@ -80,7 +88,7 @@ CHECK_HASH_LIST()
 		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
 		if [[ $? = "0" ]]; then
 			echo -n "$i: "
-			$igreen; echo "OK" ;$white
+			$bgreen; echo "OK" ;$white
 		else
 			echo -n "$i: "
 			$bred; echo "FAILED" ;$white
@@ -93,7 +101,7 @@ CHECK_HASH_LIST()
 			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
 			if [[ $? = "0" ]]; then
 				echo -n "$i: "
-				$igreen; echo "OK" ;$white
+				$bgreen; echo "OK" ;$white
 			else
 				echo -n "$i: "
 				$bred; echo "FAILED" ;$white
@@ -102,6 +110,71 @@ CHECK_HASH_LIST()
 		fi
 	done
 	if [[ $hashFail = "true" ]]; then
+		$bred; echo -n "monero-bash error: "
+		$bwhite; echo "hash check has failed"
+		$white; echo "Exiting for safety..."
+		exit 1
+	else
+		$bwhite; echo -n "monero-bash: "
+		$bgreen; echo "hash check success!"
+	fi
+}
+
+# checks the hash list less verbosely
+QUIET_HASH_LIST()
+{
+	# monero-bash hash
+	grep "monero-bash" "$hashlist" | sha256sum -c &>/dev/null
+	if [[ $? = "0" ]]; then
+		echo -n "monero-bash: "
+		$bgreen; echo "OK" ;$white
+	else
+		echo -n "monero-bash: "
+		$bred; echo "FAILED" ;$white
+		hashFail="true"
+	fi
+	# src file hashes
+	for i in src/* ;do
+		if [[ -f "$i" ]]; then
+			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+			[[ $? != "0" ]]&& srcHashFail="true"
+		fi
+	done
+	if [[ $srcHashFail = "true" ]]; then
+		$white; echo -n "source: "
+		$bred; echo "FAILED"
+	else
+		$white; echo -n "source: " ;$white
+		$bgreen; echo "OK" ;$white
+	fi
+	# function hashes
+	for i in src/func/* ;do
+		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+		[[ $? != "0" ]]&& funcHashFail="true"
+	done
+	if [[ $funcHashFail = "true" ]]; then
+		$white; echo -n "functions: "
+		$bred; echo "FAILED"
+	else
+		$white; echo -n "functions: " ;$white
+		$bgreen; echo "OK" ;$white
+	fi
+	# txt hashes
+	for i in src/txt/* ;do
+		if [[ $i != "src/txt/hashlist" ]]; then
+			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+			[[ $? != "0" ]]&& txtHashFail="true"
+		fi
+	done
+	if [[ $txtHashFail = "true" ]]; then
+		$white; echo -n "text: "
+		$bred; echo "FAILED"
+	else
+		$white; echo -n "text: " ;$white
+		$bgreen; echo "OK" ;$white
+	fi
+	# if any fail, print error
+	if [[ $hashFail = "true" || $srcHashFail = "true" || $funcHashFail = "true" || $txtHashFail = "true" ]]; then
 		$bred; echo -n "monero-bash error: "
 		$bwhite; echo "hash check has failed"
 		$white; echo "Exiting for safety..."
diff --git a/src/func/error b/src/func/error
--- a/src/func/error
+++ b/src/func/error
@@ -24,6 +24,19 @@ error_Exit()
 	fi
 }
 
+error_Sudo()
+{
+	if [[ $? = "0" ]]; then
+		:
+	else
+		printf "\033[1;31mmonero-bash error: \033[0;97m"
+		echo "[sudo] is needed"
+		echo "Exiting..."
+		exit
+	fi
+}
+
+
 error_Unknown()
 {
 	printf "\033[1;31mmonero-bash error:\033[0;97mUnknown command"
diff --git a/src/func/print b/src/func/print
--- a/src/func/print
+++ b/src/func/print
@@ -22,17 +22,29 @@ print_MoneroBashTitle()
 
 print_Version()
 {
-	$white; echo -n "Monero-CLI: "
-	if [[ $MONERO_CLI_OLD = "false" ]]; then
-		$bgreen; echo "$MONERO_CLI_VER"
-	else
-		$bred; echo "$MONERO_CLI_VER"
-	fi
-		$white; echo -n "monero-bash: "
-	if [[ $MONERO_BASH_OLD = "false" ]]; then
-		$bgreen; echo "$MONERO_BASH_VER"
-	else
+	$white; echo -n "monero-bash: "
+	if [[ "$MONERO_BASH_OLD" = "true" ]]; then
 		$bred; echo "$MONERO_BASH_VER"
+	else
+		$bgreen; echo "$MONERO_BASH_VER"
+	fi
+	$white; echo -n "Monero: "
+	if [[ "$MONERO_OLD" = "true" ]]; then
+		$bred; echo "$MONERO_VER"
+	else
+		$bgreen; echo "$MONERO_VER"
+	fi
+	$white; echo -n "monero-bash: "
+	if [[ "$MONERO_BASH_OLD" = "true" ]]; then
+		$bred; echo "$MONERO_BASH_VER"
+	else
+		$bgreen; echo "$MONERO_BASH_VER"
+	fi
+	$white; echo -n "monero-bash: "
+	if [[ "$MONERO_BASH_OLD" = "true" ]]; then
+		$bred; echo "$MONERO_BASH_VER"
+	else
+		$bgreen; echo "$MONERO_BASH_VER"
 	fi
 }
 
@@ -41,7 +53,7 @@ print_Usage()
     $off; echo -n "monero-bash usage: "
     $ired; echo "monero-bash <option> <more options>" ;$off
     echo
-    cat "$installDirectory/src/usage"
+    cat "$installDirectory/src/txt/usage"
     echo
     $ired; echo -n "monero-bash, "
     $white; echo -n "made by: "
@@ -56,6 +68,32 @@ print_Size()
 	du -h "$MoneroBashFolder" | tail -n 1 | awk '{print $1}'
 }
 
+print_Error()
+{
+	$ired; printf "monero-bash error: "
+	$iwhite; echo "$1"
+}
+
+print_Error_Exit()
+{
+	$ired; printf "monero-bash error: "
+	$iwhite; echo "$1"
+	$white; echo "Exiting..."
+	exit
+}
+
+# used for color coding sha256sum output
+print_OKFAILED()
+{
+	if [[ $? = "0" ]]; then
+		$white; echo -n "$1: "
+		$igreen; echo "OK" ;$white
+	else
+		$white; echo -n "$1: "
+		$bred; echo "FAILED" ;$white
+		hashFail="true"
+	fi
+}
 
 print_SeedLanguageList()
 {
