added /config/* to hashlist

diff --git a/src/debug b/src/debug
--- a/src/debug
+++ b/src/debug
@@ -54,6 +54,12 @@ PRODUCE_HASH_LIST()
 			sudo sha256sum $i >> "$hashlist"
 		fi
 	done
+	# config hashes
+	for i in config/* ;do
+		if [[ -f "$i" ]]; then
+			sudo sha256sum $i >> "$hashlist"
+		fi
+	done
 }
 
 # check hash list against current monero-bash files (with color coded output)
@@ -109,6 +115,18 @@ CHECK_HASH_LIST()
 			fi
 		fi
 	done
+	# config hashes
+	for i in config/* ;do
+		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+		if [[ $? = "0" ]]; then
+			echo -n "$i: "
+			$bgreen; echo "OK" ;$white
+		else
+			echo -n "$i: "
+			$bred; echo "FAILED" ;$white
+			hashFail="true"
+		fi
+	done
 	if [[ $hashFail = "true" ]]; then
 		$bred; echo -n "monero-bash error: "
 		$bwhite; echo "hash check has failed"
@@ -137,7 +155,7 @@ QUIET_HASH_LIST()
 	for i in src/* ;do
 		if [[ -f "$i" ]]; then
 			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
-			[[ $? != "0" ]]&& srcHashFail="true"
+			[[ $? != "0" ]]&& HashFail="true"
 		fi
 	done
 	if [[ $srcHashFail = "true" ]]; then
@@ -150,7 +168,7 @@ QUIET_HASH_LIST()
 	# function hashes
 	for i in src/func/* ;do
 		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
-		[[ $? != "0" ]]&& funcHashFail="true"
+		[[ $? != "0" ]]&& HashFail="true"
 	done
 	if [[ $funcHashFail = "true" ]]; then
 		$white; echo -n "functions: "
@@ -163,7 +181,7 @@ QUIET_HASH_LIST()
 	for i in src/txt/* ;do
 		if [[ $i != "src/txt/hashlist" ]]; then
 			grep "$i" "$hashlist" | sha256sum -c &>/dev/null
-			[[ $? != "0" ]]&& txtHashFail="true"
+			[[ $? != "0" ]]&& HashFail="true"
 		fi
 	done
 	if [[ $txtHashFail = "true" ]]; then
@@ -173,8 +191,20 @@ QUIET_HASH_LIST()
 		$white; echo -n "text: " ;$white
 		$bgreen; echo "OK" ;$white
 	fi
+	# config hashes
+	for i in config/* ;do
+		grep "$i" "$hashlist" | sha256sum -c &>/dev/null
+		[[ $? != "0" ]]&& HashFail="true"
+	done
+	if [[ $txtHashFail = "true" ]]; then
+		$white; echo -n "text: "
+		$bred; echo "FAILED"
+	else
+		$white; echo -n "text: " ;$white
+		$bgreen; echo "OK" ;$white
+	fi
 	# if any fail, print error
-	if [[ $hashFail = "true" || $srcHashFail = "true" || $funcHashFail = "true" || $txtHashFail = "true" ]]; then
+	if [[ $hashFail = "true" ]]; then
 		$bred; echo -n "monero-bash error: "
 		$bwhite; echo "hash check has failed"
 		$white; echo "Exiting for safety..."
